### ISSUE TITLE
error on length

### ISSUE THREAD

**Issue by zodman** [sdslabs/jinora#35]
```
web@ns1:~/smws.interalia.net/chat/jinora$  node_modules/.bin/coffee app.coffee
connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0

TypeError: Cannot read property 'length' of undefined
  at sendInitialPresenceEvent (/export/web/smws.interalia.net/chat/jinora/node_modules/slack-utils/rtm.js:44:28)
  at Request._callback (/export/web/smws.interalia.net/chat/jinora/node_modules/slack-utils/rtm.js:62:7)
  at Request.self.callback (/export/web/smws.interalia.net/chat/jinora/node_modules/request/request.js:198:22)
  at Request.emit (events.js:98:17)
  at Request.<anonymous> (/export/web/smws.interalia.net/chat/jinora/node_modules/request/request.js:1082:10)
  at Request.emit (events.js:117:20)
  at IncomingMessage.<anonymous> (/export/web/smws.interalia.net/chat/jinora/node_modules/request/request.js:1009:12)
  at IncomingMessage.emit (events.js:117:20)
  at _stream_readable.js:944:16
  at process._tickCallback (node.js:448:13)

**Comment by captn3m0** [comment]
What version of node are you running?

**Comment by zodman** [comment]
```
$ node_modules/.bin/coffee --version
CoffeeScript version 1.9.1
$ nodejs  --version
v0.10.37
$ node --version
v0.10.37

**Comment by zodman** [comment]
i update nodejs

```

connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0
/export/web/smws.interalia.net/chat/jinora/node_modules/slack-utils/api.js:11
    for (i = 0, len = list.length; i < len; i++) {
                          ^

TypeError: Cannot read property 'length' of undefined
  at listToHash (/export/web/smws.interalia.net/chat/jinora/node_modules/slack-utils/api.js:11:27)
  at Request._callback (/export/web/smws.interalia.net/chat/jinora/node_modules/slack-utils/api.js:45:33)
  at Request.self.callback (/export/web/smws.interalia.net/chat/jinora/node_modules/request/request.js:198:22)
  at emitTwo (events.js:100:13)
  at Request.emit (events.js:185:7)
  at Request.<anonymous> (/export/web/smws.interalia.net/chat/jinora/node_modules/request/request.js:1082:10)
  at emitOne (events.js:95:20)
  at Request.emit (events.js:182:7)
  at IncomingMessage.<anonymous> (/export/web/smws.interalia.net/chat/jinora/node_modules/request/request.js:1009:12)
  at emitNone (events.js:85:20)
  at IncomingMessage.emit (events.js:179:7)
  at endReadableNT (_stream_readable.js:906:12)
  at nextTickCallbackWith2Args (node.js:474:9)
  at process._tickCallback (node.js:388:17)

You have new mail in /var/mail/web
web@ns1:~/smws.interalia.net/chat/jinora$ node -v
v5.5.0
web@ns1:~/smws.interalia.net/chat/jinora$ nodejs -v
v5.5.0

**Comment by captn3m0** [comment]
The issue seems to be in slack-utils package. I'm supposed to be maintaining it as well: https://github.com/captn3m0/slack-utils. Will look into it if I get time.  Otherwise, granted access to few jinora contributors on the repo in case they feel like fixing it.

**Comment by tnmy44** [comment]
@zodman You have probably not properly configured API_TOKEN in the .env file.
